version: '3.4'

services:
  db:
    image: mariadb:lts
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: conduit
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 2s
      retries: 10

  api:
    image: ghcr.io/danielramosacosta/nestjs-realworld-example-app:latest
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_DATABASE: conduit
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '3000:3000'
